### ISSUE TITLE
Unsuccessful docker-compose build

### ISSUE THREAD

**Issue by rteeintersystems** [devecchijr/apiPub#4]
When running docker-compose build, I get an error message `#11 0.339 exec /irissession.sh: no such file or directory`

I suspect that the bug is after `SHELL ["/irissession.sh"]`

This is the output after running `docker-compose build --no-cache --progress=plain`

![image](https://github.com/devecchijr/apiPub/assets/169756122/9485617f-fc38-4ab4-9888-32b4239d88b2)

**Comment by cjy513203427** [comment]
The reason is that the author uses the linux environment ("$" symbol before the command) to build the docker image and we want to build it on the windows platform.

> Explanation of CRLF and LF usage on Windows and Linux platforms:
> 
> Windows: Uses CRLF (Carriage Return + Line Feed), represented as \r\n. This means that Windows systems use two characters to signify the end of a line: a carriage return (CR, ASCII 13) and a line feed (LF, ASCII 10)12.
> 
> Linux: Uses LF (Line Feed), represented as \n. Linux systems only require one character to indicate the end of a line, which is the line feed (LF, ASCII 10)12.
> 

Solution 1: ```git config --global autocrlf input```
[solution from community](https://stackoverflow.com/questions/46867754/getting-exec-user-process-caused-no-such-file-or-directory-error-when-trying). It works for someone, but not for me.

Solution 2: Installing an Ubuntu subsystem in Windows. I am using Ubuntu 22 on Windows 11. Just search for Ubuntu in the Microsoft Store. Installation takes less than 5 minutes. It has convenient file transfer between Windows and Linux. Enable Docker Desktop "WSL" integration, you can build Docker image in Linux subsystem and use image for Windows platform.

Solution 3 (Recommened): Add dos2unix to the dockerfile to deal with CRLF and LF issues. Check this [PR](https://github.com/devecchijr/apiPub/pull/5)

Solution 4: Use a Linux system to test this project.

**Comment by devecchijr** [comment]
thanks for the feedback and the solution. I've already approved the solution above and I'm closing the issue.
